<template>
  <div class="agent-page">
    <section class="hero"><div><span class="eyebrow">LEARNING COPILOT</span><h1>AI 学习智能体</h1><p>把模糊目标拆成真实课程与每周任务。Agent 负责规划和追踪，最终决定始终由你确认。</p></div><div class="trust"><b>安全执行边界</b><span>生成计划无需确认</span><span>启用计划必须确认</span><span>付费与选课不会自动执行</span></div></section>
    <section class="chat-panel"><div class="chat-head"><div><b>和 Agent 对话</b><span>课程检索、计划进度与学习建议</span></div><el-tag effect="plain">{{ lastTool ? `工具：${lastTool}` : '受控工具模式' }}</el-tag></div><div class="messages"><div v-if="!messages.length" class="welcome">试试问：“推荐 Java 微服务课程”或“我的计划完成多少了？”</div><div v-for="(m,i) in messages" :key="i" :class="['bubble',m.role]"><b>{{ m.role==='user'?'我':'Agent' }}</b><span>{{ m.content }}</span><small v-if="m.meta">{{ m.meta }}</small></div></div><div class="composer"><el-input v-model="chatText" placeholder="输入问题，按 Enter 发送" @keyup.enter="sendChat"/><el-button type="primary" :loading="chatLoading" @click="sendChat">发送</el-button></div></section>
    <el-card v-if="!plan || plan.empty" class="builder" shadow="never"><template #header><b>告诉 Agent 你想达成什么</b></template><el-form label-position="top" :model="form"><div class="grid"><el-form-item label="学习目标"><el-input v-model="form.goal" placeholder="例如：8 周内达到 Java 后端秋招面试水平" /></el-form-item><el-form-item label="学习兴趣"><el-input v-model="form.interest" placeholder="例如：Java、微服务、AI Agent" /></el-form-item><el-form-item label="当前水平"><el-select v-model="form.currentLevel"><el-option label="初学" value="beginner"/><el-option label="中级" value="intermediate"/><el-option label="进阶" value="advanced"/></el-select></el-form-item><el-form-item label="计划周数"><el-input-number v-model="form.weeks" :min="1" :max="12" /></el-form-item><el-form-item label="每周投入"><el-input-number v-model="form.hoursPerWeek" :min="1" :max="40" /><span class="unit">小时</span></el-form-item></div><el-button type="primary" size="large" :loading="loading" @click="generate">让 Agent 制定计划</el-button></el-form></el-card>
    <template v-else><section class="overview"><el-card shadow="never" class="plan-card"><div class="plan-head"><div><el-tag :type="plan.status==='ACTIVE'?'success':'warning'">{{ plan.status==='ACTIVE'?'执行中':'等待确认' }}</el-tag><h2>{{ plan.title }}</h2><p>{{ plan.agentSummary }}</p></div><el-progress type="dashboard" :percentage="plan.progress" /></div></el-card><div class="stat"><b>{{ plan.completedTasks }}/{{ plan.totalTasks }}</b><span>完成任务</span></div><div class="stat"><b>{{ plan.weeks }} 周</b><span>计划周期</span></div><div class="stat"><b>{{ plan.hoursPerWeek }}h</b><span>每周投入</span></div></section>
      <el-alert v-if="plan.status==='DRAFT'" title="这是 Agent 生成的草案，确认后才进入执行状态。" type="warning" show-icon><el-button type="primary" @click="confirmPlan">确认并启用计划</el-button></el-alert><div class="toolbar"><h2>每周行动清单</h2><el-button @click="newPlan">重新规划</el-button></div>
      <section v-for="week in weeks" :key="week" class="week"><div class="week-title"><span>W{{ String(week).padStart(2,'0') }}</span><h3>第 {{ week }} 周</h3></div><div class="tasks"><article v-for="task in tasksOf(week)" :key="task.id" :class="['task',{done:task.status==='COMPLETED'}]"><el-checkbox :model-value="task.status==='COMPLETED'" :disabled="plan.status!=='ACTIVE'" @change="toggle(task)"/><div><b>{{ task.title }}</b><p>{{ task.description }}</p><small>{{ task.courseTitle || '项目实践' }} · {{ task.estimatedMinutes }} 分钟</small></div></article></div></section>
    </template>
  </div>
</template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue';import{ElMessage}from'element-plus';import{agentApi}from'@/api/agent'
const loading=ref(false),plan=ref(null),chatLoading=ref(false),chatText=ref(''),conversationId=ref(''),lastTool=ref(''),messages=ref([]),form=reactive({goal:'',interest:'',currentLevel:'beginner',weeks:8,hoursPerWeek:14});const weeks=computed(()=>Array.from({length:plan.value?.weeks||0},(_,i)=>i+1));const tasksOf=w=>(plan.value?.tasks||[]).filter(t=>t.weekNo===w)
async function load(){plan.value=(await agentApi.current()).data}async function generate(){if(!form.goal.trim()||!form.interest.trim()){ElMessage.warning('请填写学习目标和兴趣');return}loading.value=true;try{plan.value=(await agentApi.preview({...form})).data}finally{loading.value=false}}async function confirmPlan(){plan.value=(await agentApi.confirm(plan.value.id)).data;ElMessage.success('计划已启用')}async function toggle(t){plan.value=(await(t.status==='COMPLETED'?agentApi.reopen(t.id):agentApi.complete(t.id))).data}function newPlan(){plan.value=null}async function sendChat(){const text=chatText.value.trim();if(!text||chatLoading.value)return;messages.value.push({role:'user',content:text});chatText.value='';chatLoading.value=true;try{const r=await agentApi.chat({conversationId:conversationId.value||null,message:text});conversationId.value=r.data.conversationId;lastTool.value=r.data.toolName||'';messages.value.push({role:'assistant',content:r.data.reply,meta:`${r.data.modelUsed} · ${r.data.latencyMs} ms`});if(r.data.toolName==='get_current_plan')await load()}finally{chatLoading.value=false}}onMounted(load)
</script>
<style scoped>
.agent-page{max-width:1200px;margin:0 auto;padding:28px 16px 64px;color:#15233b}.hero{display:flex;justify-content:space-between;gap:32px;padding:38px;border-radius:24px;background:linear-gradient(135deg,#071c34,#123f63);color:white;margin-bottom:24px}.hero h1{font-size:36px;margin:8px 0}.hero p{max-width:650px;color:#cfe1ef;line-height:1.8}.eyebrow{color:#62d8c7;font-weight:700;letter-spacing:2px}.trust{display:flex;min-width:230px;flex-direction:column;gap:9px;padding:18px;border:1px solid #ffffff2b;border-radius:16px;background:#ffffff0d}.trust span{font-size:13px;color:#d6e4ee}.builder,.plan-card{border-radius:18px}.grid{display:grid;grid-template-columns:2fr 2fr 1fr 1fr 1fr;gap:16px}.unit{margin-left:8px;color:#7b8798}.overview{display:grid;grid-template-columns:1fr 150px 150px 150px;gap:16px;margin-bottom:20px}.plan-head{display:flex;justify-content:space-between;align-items:center;gap:18px}.plan-head h2{margin:12px 0 6px}.plan-head p{color:#65758b}.stat{border-radius:18px;background:#f4f8fb;padding:28px 18px;display:flex;flex-direction:column;justify-content:center}.stat b{font-size:24px}.stat span{color:#718096;margin-top:8px}.toolbar{display:flex;align-items:center;justify-content:space-between;margin-top:28px}.week{display:grid;grid-template-columns:120px 1fr;gap:20px;margin:18px 0}.week-title span{color:#159c8c;font-weight:800}.week-title h3{margin:6px 0}.tasks{display:grid;gap:10px}.task{display:flex;gap:14px;padding:18px;border:1px solid #e6ebf0;border-radius:14px;background:#fff}.task p{margin:7px 0;color:#59677a}.task small{color:#8290a3}.task.done{opacity:.58;background:#f6faf9}.task.done b{text-decoration:line-through}@media(max-width:900px){.hero{flex-direction:column}.grid,.overview{grid-template-columns:1fr}.week{grid-template-columns:1fr}.trust{min-width:0}}
.chat-panel{margin-bottom:24px;padding:20px;border:1px solid #dfe8ef;border-radius:18px;background:#fff}.chat-head,.chat-head>div{display:flex;align-items:center;justify-content:space-between;gap:14px}.chat-head span{font-size:13px;color:#7a8797}.messages{max-height:280px;overflow:auto;margin:16px 0;display:flex;flex-direction:column;gap:10px}.welcome{text-align:center;padding:24px;color:#8090a4;background:#f6f9fb;border-radius:12px}.bubble{max-width:76%;padding:12px 15px;border-radius:14px;display:flex;flex-direction:column;gap:5px}.bubble.user{align-self:flex-end;background:#163f63;color:white}.bubble.assistant{align-self:flex-start;background:#eef5f6}.bubble small{opacity:.65}.composer{display:flex;gap:10px}
</style>
